_extends: mono-repo-release-drafter:.github/release-drafter.yml
name-template: 'Release: apps-blog v$RESOLVED_VERSION'
tag-template: 'apps-blog-v$RESOLVED_VERSION'
tag-prefix: apps-blog-v
include-paths:
  - "apps/blog/"
