_extends: mono-repo-release-drafter:.github/release-drafter.yml
name-template: 'Release: packages-utils v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION-packages-utils'
tag-prefix: v
include-paths:
  - "packages/utils"
