_extends: mono-repo-release-drafter:.github/release-drafter.yml
name-template: 'Release: apps-blog v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION-apps-blog'
tag-prefix: v
include-paths:
  - "apps/blog"
