_extends: mono-repo-release-drafter:.github/release-drafter.yml
name-template: 'Release: apps-blog v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION-apps-blog'
tag-prefix: v
include-paths:
  - "apps/blog"
