_extends: mono-repo-release-drafter:.github/release-drafter.yml
name-template: 'Release: packages-utils v$RESOLVED_VERSION'
tag-template: 'packages-utils-v$RESOLVED_VERSION'
tag-prefix: packages-utils-v
include-paths:
  - "packages/utils/"
