categories:
  - title: 'New Features'
    labels:
      - 'feature'

  - title: 'Improvements'
    labels:
      - 'improvement'

  - title: 'Bug Fixes'
    labels:
      - 'bug'

  - title: 'Hotfix'
    labels:
      - 'hotfix'

  - title: 'Maintenances'
    labels:
      - 'ci'
      - 'docs'
      - 'refactoring'
      - 'styles'
      - 'typo'
      - 'test'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  default: patch
template: |
  ## Changes

  $CHANGES
