name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          
      - uses: pnpm/action-setup@v2
        with:
          version: 7.15.0
          
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint
        
      - name: Format Check
        run: pnpm format

      - name: Test
        run: pnpm test:ci
