
name: Release Drafter

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  app-blog:
    name: '[apps/blog] Draft release'
    runs-on: ubuntu-20.04
    steps:
      - uses: release-drafter/release-drafter@09c613e259eb8d4e7c81c2cb00618eb5fc4575a7 # v5.25.0
        with:
          config-name: release-drafter-apps-blog.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  packages-util:
    name: '[packages/utils] Draft release'
    runs-on: ubuntu-20.04
    steps:
      - uses: release-drafter/release-drafter@09c613e259eb8d4e7c81c2cb00618eb5fc4575a7 # v5.25.0
        with:
          config-name: release-drafter-packages-utils.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
